#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-guacamole-update event
#--------------------------------------------------

my $event = "nethserver-guacamole-update";

event_actions($event, 
  'initialize-default-databases' => '00',
  'nethserver-guacamole-conf' => '02' #must be executed before template expansion
);

event_templates($event, qw(
  /etc/guacamole/guacamole.properties
  /etc/fail2ban/jail.d/01-guacamole.conf
  /etc/fail2ban/filter.d/guacamole.conf
  /etc/shorewall/blrules

));

event_services($event, 'httpd' => 'reload',
                       'tomcat' => 'restart',
                       'guacd' => 'restart');

#
# nethserver-sssd-save event
#

event_templates('nethserver-sssd-save',qw(
  /etc/guacamole/guacamole.properties
));

event_services('nethserver-sssd-save', qw(
  tomcat restart
));

#
# nethserver-fail2ban-save event
#

event_templates('nethserver-fail2ban-save',qw(
  /etc/fail2ban/jail.d/01-guacamole.conf
  /etc/fail2ban/filter.d/guacamole.conf
  /etc/shorewall/blrules
));
