#!/bin/bash

# make dirs

mkdir -p /etc/guacamole /usr/share/tomcat/.guacamole/ /var/lib/guacamole/lib/ /etc/fail2ban/filter.d/ /etc/fail2ban/jail.d/

# create symbolic links

ln -fs /var/lib/guacamole/guacamole.war /var/lib/tomcat/webapps
ln -fs /etc/guacamole/guacamole.properties /usr/share/tomcat/.guacamole/
ln -fs /var/lib/guacamole/lib/ /usr/share/tomcat/.guacamole/
ln -fs /var/lib/guacamole/extensions/ /usr/share/tomcat/.guacamole/
ln -fs /usr/local/lib/freerdp/guac* /usr/lib64/freerdp
ln -fs /usr/share/java/mysql-connector-java.jar /var/lib/guacamole/lib/

# remove guacamole dir to make guacamole.war update work as tomcat does not recognize a changed war file behind a symlink
if [ -d /var/lib/tomcat/webapps/guacamole ] ; then
  rm -Rf /var/lib/tomcat/webapps/guacamole
fi

# use guacamole mysql password
pass=$(perl -e "use NethServer::Password; print NethServer::Password::store('guacamole') || die('Could not read guacamole password!');")

if [ ! -d /var/lib/mysql/guacamole ] ; then
  # create db, role and schema if not exists
  mysql -e "CREATE DATABASE guacamole;"
  mysql -e "GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole.* TO 'guacamole'@'localhost' IDENTIFIED BY '$pass';"
  mysql -e "FLUSH PRIVILEGES;"
  # fill DB
  cat /opt/guacamole/*.sql | mysql -Dguacamole
else
  if [ $(mysql -ss -e "SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema = 'guacamole' AND table_name = 'guacamole_entity');") == 0 ] ; then
    # update DB if not already updated
    cat /opt/guacamole/upgrade/upgrade-pre-0.9.14.sql /opt/guacamole/upgrade/upgrade-pre-1.0.0.sql | mysql -Dguacamole
    mysql -e "GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole.* TO 'guacamole'@'localhost' IDENTIFIED BY '$pass';"
    mysql -e "FLUSH PRIVILEGES;"
  fi
fi
